# What do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc # This must match exactly the name of persistentVolumeClaim in db.yaml file
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
